dependencies:
- alias: zeebe
  name: zeebe-cluster
  repository: http://helm.zeebe.io
  version: 0.0.113
- alias: zeebe-operate
  name: zeebe-operate
  repository: http://helm.zeebe.io
  version: 0.0.24
  condition: "operate.enabled"

